"""add subjects interviews and interview scoping

Revision ID: f85e3e6c321f
Revises: 158206acc58b
Create Date: 2026-06-24 22:26:29.340898

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f85e3e6c321f'
down_revision: Union[str, None] = '158206acc58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )

    # Seed the subject catalog - sap-integration-suite is the one with a real ingested
    # corpus (the existing 5,599 documents rows); the others are catalog-only placeholders
    # so the UI can show them as "coming soon" without any ingestion work yet.
    sap_subject_id = uuid.uuid4()
    now = datetime.now(timezone.utc)
    subjects_table = sa.table(
        'subjects',
        sa.column('id', sa.UUID()), sa.column('slug', sa.String()), sa.column('name', sa.String()),
        sa.column('status', sa.String()), sa.column('description', sa.String()),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(subjects_table, [
        {'id': sap_subject_id, 'slug': 'sap-integration-suite', 'name': 'SAP Integration Suite',
         'status': 'available', 'description': 'SAP Cloud Integration / Integration Suite', 'created_at': now},
        {'id': uuid.uuid4(), 'slug': 'salesforce', 'name': 'Salesforce',
         'status': 'coming_soon', 'description': '', 'created_at': now},
        {'id': uuid.uuid4(), 'slug': 'servicenow', 'name': 'ServiceNow',
         'status': 'coming_soon', 'description': '', 'created_at': now},
    ])

    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_table('interview_subjects',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interview_id', 'subject_id')
    )
    op.create_table('qa_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_entries_interview_id'), 'qa_entries', ['interview_id'], unique=False)
    op.create_index(op.f('ix_qa_entries_user_id'), 'qa_entries', ['user_id'], unique=False)
    op.drop_index('ix_kb_entries_user_id', table_name='kb_entries')
    op.drop_table('kb_entries')

    # documents already has 5,599 real ingested rows - add subject_id as nullable first,
    # backfill them all to the sap-integration-suite subject (both existing sources -
    # sap-integration-suite-docs and sap-learning-courses - belong to that one subject),
    # then tighten to NOT NULL.
    op.add_column('documents', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.execute(sa.text("UPDATE documents SET subject_id = :sid").bindparams(sid=sap_subject_id))
    op.alter_column('documents', 'subject_id', nullable=False)
    op.create_index(op.f('ix_documents_subject_id'), 'documents', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.add_column('history_entries', sa.Column('interview_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_history_entries_interview_id'), 'history_entries', ['interview_id'], unique=False)
    op.create_foreign_key(None, 'history_entries', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.add_column('materials', sa.Column('interview_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_materials_interview_id'), 'materials', ['interview_id'], unique=False)
    op.create_foreign_key(None, 'materials', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_index(op.f('ix_materials_interview_id'), table_name='materials')
    op.drop_column('materials', 'interview_id')
    op.drop_constraint(None, 'history_entries', type_='foreignkey')
    op.drop_index(op.f('ix_history_entries_interview_id'), table_name='history_entries')
    op.drop_column('history_entries', 'interview_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_subject_id'), table_name='documents')
    op.drop_column('documents', 'subject_id')
    op.create_table('kb_entries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('use_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='kb_entries_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kb_entries_pkey')
    )
    op.create_index('ix_kb_entries_user_id', 'kb_entries', ['user_id'], unique=False)
    op.drop_index(op.f('ix_qa_entries_user_id'), table_name='qa_entries')
    op.drop_index(op.f('ix_qa_entries_interview_id'), table_name='qa_entries')
    op.drop_table('qa_entries')
    op.drop_table('interview_subjects')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_table('subjects')
    # ### end Alembic commands ###
